### ISSUE TITLE
Spark overrides user specified Breeze Version causing error for Spark 1.2

### ISSUE THREAD

**Issue by reisepass** [dalab/dissolve-struct#22]
It appears that when running Dissolve on Spark 1.2 it preferentially uses its own version of breeze which is 0.10 https://github.com/apache/spark/blob/branch-1.2/mllib/pom.xml . Hence we should throw an error if someone tires to use anything below spark 1.3   ( https://github.com/apache/spark/blob/branch-1.3/mllib/pom.xml )

**Comment by tribhuvanesh** [comment]
I think it would be better to have a working (with non-optimal breeze computations) solution on Spark < 1.3, rather than error out. 
Instead, I've updated the documentation recommending 1.3+ when run in stand-alone mode.
(In case the user runs within Eclipse under default settings, the versioning will be handled correctly.)
